{% set name = "fonticon-fontawesome6" %}
{% set version = "6.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 69d31f0d803bd1f7ec8b8f72066814f5f81c710666b496397ec2efa6272d5189

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - fonticon_fa6
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyapp-kit/fonticon-fontawesome6
  summary: 'FontAwesome 6 extension for superqt font icons'
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - src/fonticon_fa6/fonts/LICENSE.txt
  doc_url: https://pyapp-kit.github.io/superqt/utilities/fonticon/
  dev_url: https://github.com/pyapp-kit/fonticon-fontawesome6

extra:
  recipe-maintainers:
    - tlambert03
